apiVersion: v1
kind: ConfigMap
metadata:
  name: otg-api-config
  namespace: openthreatgrid
data:
  ENVIRONMENT: "production"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_EVENT_QUEUE: "otg:events"
  MAX_BATCH_SIZE: "1000"
